### ISSUE TITLE
Images in README Require Update

### ISSUE THREAD

**Issue by christopher-m-hosmer** [mitre/saf-training-lab-environment#4]
## Problems

* All [README.md](https://github.com/mitre/saf-training-lab-environment#readme) images that include script names require an update so the new script names are displayed.

* All [README.md](https://github.com/mitre/saf-training-lab-environment#readme) images that include script output require an update so the documented output matches the actual output.

## Examples

* __Update Script Names__: (https://user-images.githubusercontent.com/79539195/213515461-4c13b23a-1cd1-4e92-9d7b-3128a583d09a.png)

* __Update Script Output__: (https://user-images.githubusercontent.com/79539195/213518549-79a83522-4bcc-412c-9178-7130b1bae4e5.png)

* __Update Script Output__: (https://user-images.githubusercontent.com/79539195/213518892-a50e0044-f1ae-43bb-bbf4-5a48af3ccb5e.png)

**Comment by Amndeep7** [comment]
Resolved here: 51edccf4a8dee7e38ec28d46a1564d6069b25fbd

Added a graphic to showcase the form for creating the fork, updated the 'what should the codespace look like' graphic, updated the 'what should the terminal look like after running the build-lab script' graphic, updated the sample output for the test-lab script, and deleted the test-lab script graphic since it provided no additional value on top of the sample output that was already pasted in as text
